In [1]:
import pandas as pd
import sqlite3

In [5]:
conn = sqlite3.connect("database.sqlite")

In [6]:
df = pd.read_sql_query("SELECT * FROM Salaries", conn)

In [8]:
df.shape

(148653, 13)

In [9]:
df.columns

Index(['Id', 'EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year', 'Notes', 'Agency',
       'Status'],
      dtype='object')

## **What is the average TotalPayBenefits for each JobTitle? exclude ('Not Provided', 'Not provided')**

In [18]:
df = df[df["JobTitle"] != "Not Provided"]
df = df[df["JobTitle"] != "Not provided"]

Avg = df.groupby("JobTitle")["TotalPayBenefits"].mean()

Avg

JobTitle
ACCOUNT CLERK                                     44035.664337
ACCOUNTANT                                        47429.268000
ACCOUNTANT INTERN                                 29031.742917
ACPO,JuvP, Juv Prob (SFERS)                       80266.370000
ACUPUNCTURIST                                     67594.400000
                                                      ...
X-RAY LABORATORY AIDE                             52705.880385
X-Ray Laboratory Aide                             69521.123200
YOUTH COMMISSION ADVISOR, BOARD OF SUPERVISORS    53632.870000
Youth Comm Advisor                                60118.550000
ZOO CURATOR                                       66686.560000
Name: TotalPayBenefits, Length: 2158, dtype: float64

## **Show The JobTitle and Overtime Pay for All Employees With Overtime Pay greater than 50000**

In [19]:
df["OvertimePay"] = pd.to_numeric(df["OvertimePay"])

In [20]:
Pay = df[df["OvertimePay"] > 50000][["JobTitle", "OvertimePay"]]

Pay

                                                JobTitle  OvertimePay
1                        CAPTAIN III (POLICE DEPARTMENT)    106088.18
2                   WIRE ROPE CABLE MAINTENANCE MECHANIC     56120.71
5                     BATTALION CHIEF, (FIRE DEPARTMENT)     89062.90
7                     BATTALION CHIEF, (FIRE DEPARTMENT)     86362.68
9       ASSISTANT CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)     71344.88
...                                                  ...          ...
118287                                  Transit Operator     51625.42
118341                                  Transit Operator     52550.53
119449                          Track Maintenance Worker     50265.23
119606                         Diagnostic Imaging Tech I     74935.96
120203                           Parking Control Officer     54738.36

[2164 rows x 2 columns]

## **What is the total number of unique employees? exclude ('Not Provided', 'Not provided')**

In [23]:
df = df[df["EmployeeName"] != "Not Provided"]
df = df[df["EmployeeName"] != "Not provided"]

unique_employees = df["EmployeeName"].nunique()

unique_employees

110808

## **Show The Top 10 highest Paid Employees**

In [15]:
Top_10 = df[
    ["EmployeeName", "JobTitle", "TotalPayBenefits"]
].sort_values(
    "TotalPayBenefits",
    ascending=False
).head(10)

Top_10

,EmployeeName,JobTitle,TotalPayBenefits
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,567595.43
110530,David Shinn,Deputy Chief 3,510732.68
110531,Amy P Hart,Asst Med Examiner,479652.21
110532,William J Coaker Jr.,Chief Investment Officer,436224.36
72924,Gregory P Suhr,Chief of Police,425815.28
72925,Joanne M Hayes-White,"Chief, Fire Department",422353.40
110533,Gregory P Suhr,Chief of Police,418019.22
110534,Joanne M Hayes-White,"Chief, Fire Department",417435.10
110535,Ellen G Moffatt,Asst Med Examiner,415767.94
36158,Gary Altenberg,"Lieutenant, Fire Suppression",407274.78

## **Show All Employees Ordered By Their TotalPay Benefits In Descending Order**

In [16]:
Employees = df[
    ["EmployeeName", "JobTitle", "TotalPayBenefits"]
].sort_values(
    "TotalPayBenefits",
    ascending=False
)

Employees

,EmployeeName,JobTitle,TotalPayBenefits
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,567595.43
110530,David Shinn,Deputy Chief 3,510732.68
110531,Amy P Hart,Asst Med Examiner,479652.21
110532,William J Coaker Jr.,Chief Investment Officer,436224.36
72924,Gregory P Suhr,Chief of Police,425815.28
...,...,...,...
148633,David M Turner,Transit Car Cleaner,0.00
110527,Timothy E Gibson,Police Officer 3,-2.73
110528,Mark E Laherty,Police Officer 3,-8.20
110529,David P Kucia,Police Officer 3,-33.89
148652,Joe Lopez,"Counselor, Log Cabin Ranch",-618.13